### ISSUE TITLE
Images Forced To Use Original Version Not Resized Version

### ISSUE THREAD

**Issue by curranabell** [jawngee/ILab-Media-Tools#7]
Hi,

I upgraded Media Cloud from 2.02 on a client's site to 2.1 and when I did this it now forces the images that are being pulled into a grid I created to use the full version of the image not a cropped version. I had to revert back to 2.02 but would like to update the site. I cloned the site to a dev site and upgraded to show you what I mean.

2.02 - https://rsmdesign.com

2.1 - After update https://dev.rsmdesign.com

I go into the grid and then choose to pull in the cropped version of the image, the grid is then temporarily fixed, I save the page and it looks good, then I reload it and it is back to pulling in the original images.

I can give you login credentials to the dev site if you need them.

If you have a solution for this that would help me out sooo much!

Thanks,

Curran

**Comment by jawngee** [comment]
I'm looking at the grid on both sites and they seem to be using the same image URLs?

From the live site:

![current-site](https://user-images.githubusercontent.com/44449/32579588-277020ee-c514-11e7-868f-0dde03e9a8b0.png)

From the dev site:

![dev-site](https://user-images.githubusercontent.com/44449/32579602-3649a702-c514-11e7-9ffc-aad6f4680008.png)

I think the issue is with the actual CSS on the `.pp-content-post-grid` class.  On the dev site you have `display: flex` in the class, but on the live site you don't.  When I turn that off in the web inspector the grids look identical.  They definitely are using the same image URLs too.

![home_-_rsm_design](https://user-images.githubusercontent.com/44449/32579934-9ea0585e-c515-11e7-9425-e9ad7734d998.png)

**Comment by curranabell** [comment]
Hey Jon,

Thank you so much for looking into this I really appreciate it! I have been trying to figure this out for a while now and really appreciate your help and quick response.

Also plugin has been working flawlessly besides this, great work. 

Cheers,

Curran
